[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 5173
  autoLaunch = false

[functions]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "20"
